name: 'Auto Release draft'
description: 'Drafts a GitHub release with the changes introduced by the newly created version tag'
author: 'Prabhat Pal'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN used to authenticate to the current'
    required: true
outputs:
  release-url:
    description: 'The URL of the drafted GitHub release'
runs:
  using: 'node12'
  main: 'dist/index.js'
