name: Test
on:
    push:
        branches:
            - master
jobs:
    build:
        name: Unit Test
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: 
                    - windows-latest
                    - ubuntu-latest
        steps:
            - name: Get the sources
              uses: actions/checkout@v2
            - name: Create a release draft
              id: create-release-draft
              uses: ./
            - name: Print URL of the release draft
              run: echo ${{ steps.create-release-draft.outputs.release-url }}
